class CreateSurveys < ActiveRecord::Migration
  def change
    create_table :surveys do |t|
       t.belongs_to :user

       t.string :date_restaurant_1
       t.string :date_restaurant_2
       t.string :date_restaurant_3
       t.string :lunch_restaurant_1
       t.string :lunch_restaurant_2
       t.string :lunch_restaurant_3
       t.string :date_night_1
       t.string :date_night_2
       t.string :date_night_3
       t.string :public_place_1
       t.string :public_place_2
       t.string :public_place_3
       t.string :do_for_fun_1
       t.string :do_for_fun_2
       t.string :do_for_fun_3
       t.string :cultural_things_1
       t.string :cultural_things_2
       t.string :cultural_things_3
       t.string :doctor_obgyn
       t.string :doctor_pediatrician
       t.string :doctor_general
       t.string :doctor_chiropractor
       t.string :doctor_earnosethroat
       t.string :doctor_vet
       t.string :doctor_other
       t.string :deliver_baby_1
       t.string :deliver_baby_2
       t.string :deliver_baby_3
       t.string :childcare_1
       t.string :childcare_2
       t.string :childcare_3
       t.integer :babysitter_pay
       t.string :family_restaurant_1
       t.string :family_restaurant_2
       t.string :family_restaurant_3
       t.string :family_restaurant_4
       t.string :family_restaurant_5
       t.string :kid_activity_1
       t.string :kid_activity_2
       t.string :kid_activity_3
       t.string :kid_activity_4
       t.string :kid_activity_5
       t.string :good_school_1
       t.string :good_school_2
       t.string :good_school_3
       t.string :bad_school_1
       t.string :bad_school_2
       t.string :bad_school_3
       t.string :contact_gymnastics
       t.string :contact_dance
       t.string :contact_karate
       t.string :contact_ballet
       t.string :contact_baseball
       t.string :contact_basketball
       t.string :contact_soccer
       t.string :contact_football
       t.string :contact_lacrosse
       t.string :contact_music
       t.string :contact_art
       t.string :contact_swimming
       t.string :contact_any_other_kid_stuff
       t.string :gym_1
       t.string :gym_2
       t.string :gym_3
       t.string :religious_1
       t.string :religious_2
       t.string :religious_3
       t.string :bad_area_1
       t.string :bad_area_2
       t.string :bad_area_3
       t.string :good_area_1
       t.string :good_area_2
       t.string :good_area_3
       t.string :bad_traffic_1
       t.string :bad_traffic_2
       t.string :bad_traffic_3
       t.string :good_commute_1
       t.string :good_commute_2
       t.string :good_commute_3
       t.string :apt_complex_1
       t.string :apt_complex_2
       t.string :apt_complex_3
       t.string :cost_of_living
       t.string :employers_military_1
       t.string :employers_military_2
       t.string :employers_military_3
       t.string :schools_military_1
       t.string :schools_military_2
       t.string :schools_military_3
       t.string :involved_strollers
       t.string :involved_mops
       t.string :involved_volunteering
       t.string :involved_breastfeeding
       t.string :involved_cooking_class
       t.string :involved_group_fitness
       t.string :involved_political
       t.string :involved_base_or_command
       t.string :grocery_store_1
       t.string :grocery_store_2
       t.string :grocery_store_3
       t.string :drug_store_1
       t.string :drug_store_2
       t.string :drug_store_3
       t.string :walmart_1
       t.string :walmart_2
       t.string :walmart_3
       t.string :hairdresser_1
       t.string :hairdresser_2
       t.string :hairdresser_3
       t.string :spa_1
       t.string :spa_2
       t.string :spa_3
       t.string :nail_place_1
       t.string :nail_place_2
       t.string :nail_place_3
       t.string :coffee
       t.string :dry_cleaner
       t.string :fast_food
       t.string :hardware
       t.string :craft
       t.string :office
       t.string :clothing
       t.string :shoe
       t.string :pet
       t.string :handyman
       t.string :cell_phone_provider
       t.string :cable_provider
       t.integer :monthly_cable_bill
       t.string :electric_company
       t.integer :monthly_electrical_bill
       t.string :gas_company
       t.integer :monthly_gas_bill
       t.string :hows_the_traffic
       t.string :hows_the_drivers
       t.string :weather_winter
       t.string :weather_spring
       t.string :weather_summer
       t.string :weather_fall
       t.integer :city_id
       t.string :neighborhood
       t.integer :zipcode
       t.string :education_level
       t.string :gender
       t.string :self_military_employment
       t.string :self_branch
       t.string :self_command
       t.integer :self_commute
       t.string :self_rank
       t.boolean :self_marital_status
       t.string :spouse_military_employment
       t.string :spouse_branch
       t.string :spouse_command
       t.integer :spouse_commute
       t.string :spouse_rank
       t.string :annual_household_income
       t.boolean :kid_status
       t.integer :kid_number
       t.string :own_or_rent
       t.integer :square_feet_rental
       t.integer :square_feet_house
       t.integer :mothly_rent
       t.string :recommend_rent_or_buy
       t.string :nearby_home_value
       t.string :age_of_homes
       t.string :yard_size
       t.boolean :is_there_POA
       t.string :POA_behavior
       t.string :subdivision
       t.timestamps
     end
     add_index :surveys, :user_id
    end
end
