class CreateSurvey < ActiveRecord::Migration
  def change
    create_table :surveys do |t|
      t.belongs_to :user

      t.string :date_restaurant_1, :default => ""
      t.string :date_restaurant_2, :default => ""
      t.string :date_restaurant_3, :default => ""
      t.string :lunch_restaurant_1, :default => ""
      t.string :lunch_restaurant_2, :default => ""
      t.string :lunch_restaurant_3, :default => ""
      t.string :date_night_1, :default => ""
      t.string :date_night_2, :default => ""
      t.string :date_night_3, :default => ""
      t.string :public_place_1, :default => ""
      t.string :public_place_2, :default => ""
      t.string :public_place_3, :default => ""
      t.string :do_for_fun_1, :default => ""
      t.string :do_for_fun_2, :default => ""
      t.string :do_for_fun_3, :default => ""
      t.string :cultural_things_1, :default => ""
      t.string :cultural_things_2, :default => ""
      t.string :cultural_things_3, :default => ""
      t.string :doctor_obgyn, :default => ""
      t.string :doctor_pediatrician, :default => ""
      t.string :doctor_general, :default => ""
      t.string :doctor_chiropractor, :default => ""
      t.string :doctor_earnosethroat, :default => ""
      t.string :doctor_vet, :default => ""
      t.string :deliver_baby_1, :default => ""
      t.string :deliver_baby_2, :default => ""
      t.string :deliver_baby_3, :default => ""
      t.string :childcare_1, :default => ""
      t.string :childcare_2, :default => ""
      t.string :childcare_3, :default => ""
      t.integer :babysitter_pay, :default => ""
      t.string :family_restaurant_1, :default => ""
      t.string :family_restaurant_2, :default => ""
      t.string :family_restaurant_3, :default => ""
      t.string :family_restaurant_4, :default => ""
      t.string :family_restaurant_5, :default => ""
      t.string :kid_activity_1, :default => ""
      t.string :kid_activity_2, :default => ""
      t.string :kid_activity_3, :default => ""
      t.string :kid_activity_4, :default => ""
      t.string :kid_activity_5, :default => ""
      t.string :good_school_1, :default => ""
      t.string :good_school_2, :default => ""
      t.string :good_school_3, :default => ""
      t.string :bad_school_1, :default => ""
      t.string :bad_school_2, :default => ""
      t.string :bad_school_3, :default => ""
      t.string :contact_gymnastics, :default => ""
      t.string :contact_dance, :default => ""
      t.string :contact_karate, :default => ""
      t.string :contact_ballet, :default => ""
      t.string :contact_baseball, :default => ""
      t.string :contact_basketball, :default => ""
      t.string :contact_soccer, :default => ""
      t.string :contact_football, :default => ""
      t.string :contact_lacrosse, :default => ""
      t.string :contact_music, :default => ""
      t.string :contact_art, :default => ""
      t.string :contact_swimming, :default => ""
      t.string :contact_any_other_kid_stuff, :default => ""
      t.string :gym_1, :default => ""
      t.string :gym_2, :default => ""
      t.string :gym_3, :default => ""
      t.string :religious_1, :default => ""
      t.string :religious_2, :default => ""
      t.string :religious_3, :default => ""
      t.string :bad_area_1, :default => ""
      t.string :bad_area_2, :default => ""
      t.string :bad_area_3, :default => ""
      t.string :good_area_1, :default => ""
      t.string :good_area_2, :default => ""
      t.string :good_area_3, :default => ""
      t.string :bad_traffic_1, :default => ""
      t.string :bad_traffic_2, :default => ""
      t.string :bad_traffic_3, :default => ""
      t.string :good_commute_1, :default => ""
      t.string :good_commute_2, :default => ""
      t.string :good_commute_3, :default => ""
      t.string :apt_complex_1, :default => ""
      t.string :apt_complex_2, :default => ""
      t.string :apt_complex_3, :default => ""
      t.string :cost_of_living, :default => ""
      t.string :employers_military_1, :default => ""
      t.string :employers_military_2, :default => ""
      t.string :employers_military_3, :default => ""
      t.string :schools_military_1, :default => ""
      t.string :schools_military_2, :default => ""
      t.string :schools_military_3, :default => ""
      t.string :involved_strollers, :default => ""
      t.string :involved_mops, :default => ""
      t.string :involved_volunteering, :default => ""
      t.string :involved_breastfeeding, :default => ""
      t.string :involved_cooking_class, :default => ""
      t.string :involved_group_fitness, :default => ""
      t.string :involved_political, :default => ""
      t.string :involved_base_or_command, :default => ""
      t.string :grocery_store_1, :default => ""
      t.string :grocery_store_2, :default => ""
      t.string :grocery_store_3, :default => ""
      t.string :drug_store_1, :default => ""
      t.string :drug_store_2, :default => ""
      t.string :drug_store_3, :default => ""
      t.string :walmart_1, :default => ""
      t.string :walmart_2, :default => ""
      t.string :walmart_3, :default => ""
      t.string :hairdresser_1, :default => ""
      t.string :hairdresser_2, :default => ""
      t.string :hairdresser_3, :default => ""
      t.string :spa_1, :default => ""
      t.string :spa_2, :default => ""
      t.string :spa_3, :default => ""
      t.string :nail_place_1, :default => ""
      t.string :nail_place_2, :default => ""
      t.string :nail_place_3, :default => ""
      t.string :coffee, :default => ""
      t.string :dry_cleaner, :default => ""
      t.string :fast_food, :default => ""
      t.string :hardware, :default => ""
      t.string :craft, :default => ""
      t.string :office, :default => ""
      t.string :clothing, :default => ""
      t.string :shoe, :default => ""
      t.string :pet, :default => ""
      t.string :handyman, :default => ""
      t.string :cell_phone_provider, :default => ""
      t.string :cable_provider, :default => ""
      t.integer :monthly_cable_bill, :default => ""
      t.string :electric_company, :default => ""
      t.integer :monthly_electrical_bill, :default => ""
      t.string :gas_company, :default => ""
      t.integer :monthly_gas_bill, :default => ""
      t.string :hows_the_traffic, :default => ""
      t.string :hows_the_drivers, :default => ""
      t.string :weather_winter, :default => ""
      t.string :weather_spring, :default => ""
      t.string :weather_summer, :default => ""
      t.string :weather_fall, :default => ""
      t.integer :city_id
      t.string :neighborhood, :default => ""
      t.integer :zipcode
      t.string :education_level, :default => ""
      t.string :gender, :default => ""
      t.string :self_military_employment, :default => ""
      t.string :self_branch, :default => ""
      t.string :self_command, :default => ""
      t.integer :self_commute
      t.string :self_rank, :default => ""
      t.boolean :self_marital_status
      t.string :spouse_military_employment, :default => ""
      t.string :spouse_branch, :default => ""
      t.string :spouse_command, :default => ""
      t.integer :spouse_commute
      t.string :spouse_rank, :default => ""
      t.string :annual_household_income, :default => ""
      t.boolean :kid_status
      t.integer :kid_number

      t.timestamps
    end
    add_index :surveys, :user_id
  end
end
